# Site Settings
locale : "ko_KR"
title : "í™©ìœ¤ì„± ë¸”ë¡œê·¸"
subtitle : # site tagline that appears below site title in masthead
name : "í™©ìœ¤ì„±"
description : ğŸ¢ ğŸ§â€ ğŸ‹ï¸â€
url : "https://acafela.github.io"
baseurl : ""
repository : acafela/acafela.github.io
github_username: acafela

# Build settings
# GitHub page
theme: minima
# local
# theme: plainwhite
remote_theme: thelehhman/plainwhite-jekyll

plugins:
  - jekyll-seo-tag

plainwhite:
  name: Youn Sung Hwang
  tagline: ğŸ¢ ğŸ§â€ ğŸ‹ï¸â€
  date_format: "%Y. %-m. %-d"
  sitemap: true # set to true to generate sitemap.xml content
#  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  condensed_mobile:
    - home
    - post
    - page
  social_links:
    github: acafela
    # linkedIn: in/ìœ¤ì„±-í™©-ba4741174
    #rss: rss
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll
  navigation:
    - title: Posts
      url: "/"
    - title: Tags
      url: "/category"
    - title: About
      url: "/about"
  disqus_shortname: acafela-blog

show_excerpts: true